article/urls.py
from django.contrib import admin
from django.urls import path
from article import views

app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addarticle,name = "addarticle"),
    path('article/<int:id>/',views.detail,name = "detail"),
    path('update/<int:id>/',views.updateArticle,name = "update"),
    path('delete/<int:id>/',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),#/article sayfasına git dediğimiz için içi boş
    path('comment/<int:id>/',views.addComment,name = "comment"),

]

blog/urls.py
from django.contrib import admin
from django.urls import include, path
from user import views
from article import views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"), # ana sayfayı döndürdün diye içi boş
    path('about/', views.about, name = "about"),
    path('articles/',include("article.urls")), # 211. ders include ederek projeyi daha bait hala getiriyouz meslea.article ile ilgili olan şeyleri article.url buraya yazacağız
    path('user/',include("user.urls")), #eğer user/-- diye url girersek -- olan yerde yazan sayfaya yönlendiricek yönlendircek
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #resim ekleme işlemleriiçin gerekli

article/models.py
#HERYENİ BİR ALAN EKLEDİĞİMİZDE MESLEA TİTLE ONU VERİTABANINA SÖYLEMEK İÇİN "python3 manage.py makemigrations" dememiz gerek ve sonrasında "python3 manage.py migrate" dicez
from django.db import models
from ckeditor.fields import RichTextField

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE, verbose_name = "Yazar") # Bu alanımız user tablosunu işaret ediyor
    #onDelete = models.CASCADE ile eğer makaleyi yazan user silinirse ona ait herşey silinsin

    title = models.CharField(max_length = 50, verbose_name = "Başlık") #Title ın maksium uzunluğu 50 olsun
    # content = models.TextField(verbose_name = "İçerik")#TextField = Text Area anlamına geliyor
    content = RichTextField()
    createdDate = models.DateTimeField(auto_now_add = True, verbose_name = "Oluşturulma Tarihi") # Tarihi otomatik kaydetmesi için
    articleImage = models.FileField(blank = True, null = True, verbose_name = "Makaleye Fotoraf Ekleyin") #null = True, bu alan doluda olabilir boşta

    def __str__(self):
        return self.title # Articleın title bilgisini göstermeye yarıyor
    
    class Meta:
        ordering = ['-createdDate'] #yaparak makaleleri en son yapılana göre sıralamaya yarıyor
    
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE, verbose_name = "Makale", related_name = "comments")#related_name = "comments" dersek Article.comments diyerek comment tablosuna erişebiliyorum
    comment_author = models.CharField(max_length = 50, verbose_name = "İsim")
    comment_content = models.CharField(max_length = 200, verbose_name = "Yorum")
    comment_date = models.DateTimeField(auto_now_add = True)

    class Meta:
         ordering = ['-comment_date']

    def __str__(self):
        return self.comment_content #admin panelin de Comment(1) yerine comment in conteni görülecek
    
    

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article #bunu yaparak models dosyasındaki article ile form umuzu bağlantılı hale getirmiş oluyor
        #fields ifadesini kullanmamızı django öneriyor
        fields = ["title", "content", "articleImage"]  #djangoya title ve content alanlarından input oluştur diğerleri(tarih ve yazardan) oluşturma dedik

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404,reverse
from django.contrib.auth.decorators import login_required #loginn giriş yapılıp yapılmaduğınj kontrol edecegüiz
from .forms import ArticleForm
from django.contrib import messages
from .models import Article, Comment
# Create your views here.

#RENDER İN ALABİLECEĞİ İÇERİKLER
#request, template_name, context=None, content_type=None, status=None, using=None

#RENDER: Temel işlevi, bir Django şablonunu alıp bu şablonu verilen bağlam (context) ile birleştirerek bir HttpResponse nesnesi oluşturmaktır.

#UYARI
#İLK PARAMETREMİZ REQUEST OLMASI LAZIM

def articles(request):
    #Bu kod ile makaleleri tüm kullanıcılar görebilir 

    keyword = request.GET.get("keyword")#keyword yani arama butonun name i get request ile işlemleri yap

    if keyword: #eğer ara butonuna tıklandıysa if in aldınkai işlemleri yap
        articles = Article.objects.filter(title__contains = keyword)
        return render(request, "articles.html", {"articles":articles})
    
    else:#eğer tıklnamadıysa
        articles = Article.objects.all()
        context = {
            "articles":articles
        }
        return render(request, "articles.html",context)


    #sadece giriş yapılan kullanıcının makalelerinin gürüntlenmesi için 
    # user = request.user
    # articles = Article.objects.filter(author=user)
    # return render(request, 'articles.html', {'articles': articles})


def index(request):
    context = {
        "numbers":[10,20,30],
        "number1":20
    }
    return render(request,"index.html",context) #context ile veriyi html kodlaıyla ekrana yazdırabiliriz
    # django direk templates klasorüne otomatik şekilde bakacağı için yolunu yazmamıza gerek yok
    # return render(request,"../templates/index.html") de yapabilirdik

def about(request):
    return render(request, "about.html")
# return render(request,"../templates/about.html") de yapabilirdik

@login_required(login_url = "user:login") #bunun altındaki fonskiyonda login yapmadan erişemicez. ve eğer girilmeye çalışırlarsa login sayfasına yönlendircek
def dashboard(request):
    articles = Article.objects.filter(author = request.user)#articilelardan authoru sadece şuanki kullanıcı olan bir filtreleme
    context = {
        "articles":articles
    }
    return render(request, "dashboard.html",context)


@login_required(login_url = "user:login") #bunun altındaki fonskiyonda login yapmadan erişemicez. ve eğer girilmeye çalışırlarsa login sayfasına yönlendircek
def addarticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None) #hem yazı eklemek ayriyetten sonrada resimde yükliyebilmek için request.FILES or None ekledik

    if form.is_valid():
        article = form.save(commit=False) #commit işlemini sen yapma ben yapcam diyorum

        article.author = request.user #sisteme hangi kullanıcı girdiyse auythor otomatik onu yap diyoruz
        article.save()
        messages.success(request, "Makale Başarıyla Oluşturuldu")
    
        return redirect("index")

    context = {
        "form":form
    }

    return render(request, "addarticle.html",context) #render kısacası veriyi addarticle.html e gönder diyorum

@login_required(login_url = "user:login") #bunun altındaki fonskiyonda login yapmadan erişemicez. ve eğer girilmeye çalışırlarsa login sayfasına yönlendircek
def detail(request,id):
    # article = Article.objects.filter(id = id).first()# id si burdaki id olanı kastettim, .first() yaparak liste şeklinde yazmasını önledim ve filtre sonucunda ilk çıkan id yi yaz dedim

    article = get_object_or_404(Article.objects.filter(id = id))

    comments = article.comments.all()# article.comments.all() burdaki comments related_name olarak vermiştikya o işte

    context = {
        "article":article,
        "comments":comments
    }

    
   
    return render(request, "detail.html",context)

@login_required(login_url = "user:login") #bunun altındaki fonskiyonda login yapmadan erişemicez. ve eğer girilmeye çalışırlarsa login sayfasına yönlendircek
def updateArticle(request, id):
    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None, request.FILES or None,instance=article)#instance=article ile article içindeki hersey formun içine yazılacaktır


    # if(article.author!= request.user): #başka bir kullanıcı başka bir kullanıcının makalelerine erişim sağlıyamasın diye
    #     messages.info(request,"Bu makaleye erişiminiz yok. Lütfen bilgilerinizi tekrar kontrol ediniz!!")
    #     return redirect("index")

    if form.is_valid():
        article = form.save(commit=False) #commit işlemini sen yapma ben yapcam diyorum

        article.author = request.user #sisteme hangi kullanıcı girdiyse auythor otomatik onu yap diyoruz
        article.save()
        messages.success(request, "Makale Başarıyla Güncellendi")

        return redirect('article:detail', id = article.id) #yaparak güncellenmis makalenin sayfasına yönlendiriyor,  #article aldındaki detail nameindeki veriye git

    context = {
        "form":form
    }

    return render(request, "update.html",context)

@login_required(login_url = "user:login") #bunun altındaki fonskiyonda login yapmadan erişemicez. ve eğer girilmeye çalışırlarsa login sayfasına yönlendircek
def deleteArticle(request,id):
    article = get_object_or_404(Article, id = id)#id = id yaparak silinecek article id sini kontrol ediyor

    # if(article.author!= request.user): #başka bir kullanıcı başka bir kullanıcının makalelerine erişim sağlıyamasın diye
    #     messages.info(request,"Bu makaleye erişiminiz yok. Lütfen bilgilerinizi tekrar kontrol ediniz!!")
    #     return redirect("index")
    
    article.delete()
    messages.success(request, "Makale Başarıyla Silindi")
    
    return redirect("article:dashboard") #article aldındaki dashboard nameindeki veriye git

def addComment(request, id):
    article = get_object_or_404(Article, id = id)#gönderilen id ile aynı olan demek istedik

    if request.method == "POST":
       comment_author = request.POST.get("comment_author")#"comment_author" htmldeki input üstündeki name i 
       comment_content = request.POST.get("comment_content")# türkçesi eğer post ile yapılırsa comment_content bilgisini getir

       newComment = Comment(comment_author = comment_author, comment_content = comment_content)#comment_author = comment_author, comment_content = comment_content sağdaki değişken isimleri farklı bişey yapabilrizde

       newComment.article = article #aldığımız article bilgisini verdik

       newComment.save()

   
    return redirect(reverse("article:detail", kwargs={"id": id})) #reverse modülü ile dinamik bir url yaptık
   

templates/about.html
{% extends "layout.html" %} <!-- layout.html den miras alıyoruz-->

{% block body %}

<h3>Hakkımızda</h3>
<hr><!--Çizgi bırakmaya yarıyor-->
Herkese merhaba.Ben Mustafa Murat Coşkun.Odtü Bilgisayar Mühendisliği 4.sınıf öğrencisiyim.Yazılım Bilimi kanalını programlama ve yazılım öğrenmek isteyen gençlere ve yazılımcılara faydalı olmak ,aynı zamanda Türkiyede yazılımın ve eğitimin yükselmesi amacıyla  10 Nisan 2015 tarihinde kurdum.Şimdiye kadar elimden geldiğince video yüklemeye çalıştım.Bu kanaldaki amacım Yazılım Bilimini genel bir online akademiye dönüştürüp Türkiye’nin dört bir yanına ücretsiz bir şekilde eğitim verebilmek.Ülkemizin gençleri olarak hep beraber yazılımı ve bilimi herkese aşılamaya çalışalım.Var mısınız?
<hr>


{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3>
        <hr>

        <form action="" method="POST" enctype="multipart/form-data"> <!--enctype="multipart/form-data" resim dosyalarınıda eklenmesini sağlıyoruz-->
            {% csrf_token %}
            {{form.media}}
            {{ form|crispy }} <!--{{ form.as_p }} şablon etiketi, bir formun alanlarını HTML <p> etiketleri içerisinde göstermek için kullanılır.-->
            <br>
            <button type="submit" class="btn btn-danger">Makale Oluştur</button>
        
        </form>

    </div>
  </div>



{% endblock body %}

templates/articles.html
{% extends "layoutArticles.html" %}
{% block body %}
<div class="row">
    <div class="col-md-10 offset-md-3"><!--içerikleri ortalamak için class="col-md-10 offset-md-3" kullandık.   col-md-10 yaparak içeriklerin genişliklerini büyültüük col-md-6 da olursada daha a geniş olur-->
        <div class="col-lg-8">
            <h3>Makaleler</h3>
            <hr>
        </div>
    </div>
</div>

{% if articles %}

{% for article in articles %}

<div class="row">
    <div class="col-md-10 offset-md-3"> <!--içerikleri ortalamak için class="col-md-10 offset-md-3" kullandık.   col-md-10 yaparak içeriklerin genişliklerini büyültüük col-md-6 da olursada daha a geniş olur-->
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a><!--url 'article:detail' article.id diyerek dinamik bir şekilde o linke gidebiliyorun-->
                    <!-- Author title-->
                    <div class="text-muted fst-italic mb-2"><b>{{article.author.username}}</b> tarafından oluşturuldu</div>
                    <hr>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">{{article.createdDate}}</div>
                    <hr>
                </header>

                {% if article.articleImage %}<!--Eğer resim varsa -->
                <!-- Preview image figure-->
                <figure class="mb-4"><img class="img-fluid rounded" src="{{article.articleImage.url}}" alt="" /></figure>
                {% endif %}

                <!-- Post content-->
                <p class="lead">
                    {{article.content|safe|truncatewords:10 }} <!--safe ile yazımızın html görünümden kurtulmasını sağlıyoruz. truncatewords:10 ilede ilk 10 kelimenin görünmesini sağlıyoruz-->
                </p>
                

                <a href="/articles/article/{{article.id}}" class="btn btn-danger" style="float: right;">Devamını Oku</a><!--float ile butonu sağa yasladım-->
            </article>
        </div>
        
    </div>
</div>




{% endfor %}


{% else %}

<div class="alert alert-danger">
    Makale Bulunamadı
</div>

{% endif %}



{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
    <h3>Kontrol Paneli </h3>
    <hr>

    <p>
        Hoşgeldiniz, {{request.user.username}}
    </p>
    <hr>

    <a class="btn btn-danger" href="/articles/addarticle"> Makale Ekle </a>
    <hr>

    {% if articles %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">İd</th>
                <th scope="col">Başlık</th>
                <th scope="col">Yazar</th>
                <th scope="col">Tarih</th>
                <th scope="col">Güncelle</th>
                <th scope="col">Sil</th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles %}
                    <tr>
                        <th scope="row">{{ article.id }}</th>
                        <td><a href="/articles/article/{{article.id}}">{{ article.title }}</a></td> <!-- tıklandığında tıklanan articlın id sine git-->
                        <td>{{ article.author.username }}</td>
                        <td>{{ article.createdDate }}</td>
                        <td><a href="/articles/update/{{ article.id }}" class="btn btn-danger">Güncelle</a></td>
                        <td><a href="/articles/delete/{{ article.id }}" class="btn btn-danger">Sil</a></td>
                    </tr>
                {% endfor %}
        </tbody>
    </table>

    {% else %}
    <div class="alert alert-danger" style="text-align: center;">Henüz Bir Makaleniz Yok</div>
    {% endif %}

    

{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% block body %}

<div class="row">
    <div class="col-lg-8">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                <!-- Author title-->
                <div class="text-muted fst-italic mb-2">{{article.author.username}}</div>
                <hr>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">{{article.createdDate}}</div>
                <hr>
            </header>

            {% if article.articleImage %}<!--Eğer resim varsa -->
            <!-- Preview image figure-->
            <figure class="mb-4"><img class="img-fluid rounded" src="{{article.articleImage.url}}" alt="" /></figure>
            {% endif %}

            <!-- Post content-->
            <p class="lead">
                {{article.content|safe}} <!--safe ile yazımızın html görünümden kurtulmasını sağlıyourz-->
            </p>

        <h4>Yorumlar</h4>
        <hr>

        {% comment %} {% for %} döngüsünü kullanmadığınızda, şablon motoru comments sorgu kümesindeki her yorum nesnesini döngü içinde işleyemez. Sonuç olarak, sadece sorgu kümesindeki ilk yorum görüntülenir ve şablon motoru diğer yorumları göstermez. {% endcomment %}

        {% if comments %}
        {% for comment in comments %} 
            <!-- Single comment-->
            <div class="media mb-4">
                <img class="d-flex mr-3 rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="">
                <div class="media-body">
                <h5 class="mt-0">{{comment.comment_author}}</h5>
                <div  style="opacity: 0.7; font-size: 12px;">{{comment.comment_date}}</div>
                {{comment.comment_content}}
                
                </div>
            </div>
       
        {% endfor %}

        {% else %}
        <div class="alert alert-danger">Bu Makaleye Herhangi Bir Yorum Yazılmamış, ilk yorum yapan siz olun</div>
        
        {% endif %}

        </article>
        <div class="card my-4">
            <h5 class="card-header">Yorum Ekle:</h5>
            <div class="card-body">
              <form method="post" action="{% url "article:comment" article.id %}"><!--butona basıldığında bu url ye gi. method="post" ile güvenli bir şekilde yorumu gönder-->
                {% csrf_token %}<!--mutlaka eklememiz gerekiyor. Her formun altında olması gerekiyor-->
                <div class="form-group">
                    <label for="formGroupExampleInput">İsim</label>
                    <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi girin">
                  </div>
                <div class="form-group">
                    <label for="formGroupExampleInput">Yorum</label>
                  <textarea name = "comment_content" class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-danger" style="float: right;">Ekle</button>
              </form>
            </div>
          </div>
          </div>
          
        </div>
    </div>
</div>





{% endblock body %}

templates/index.html
{% extends "layout.html" %}
{% block body %}


<div class="jumbotron text-center">
    <h3>Yazılım Bilimi Bloğuna Hoşgeldiniz</h3>
    <p>Bu blogta geliştiriciler olarak blog yazılarınızı paylaşabilirsiniz ve insanlara yardımcı olabilirsiniz.</p>
</div>

<p>
    {% if request.user.is_authenticated %} <!--eğer user giriş yaptıysa-->

        Giriş Yapılmış, {{request.user.username}}
    {% else %}
        Giriş Yapılmamış
    {% endif %}
</p>

{% comment %} <p>
    {{number1}}
</p> {% endcomment %}

{% comment %} {% if number1 == 20 %}
    <p> Sayımız 20 ye eşittir</p>

{% else %}
<p> Sayımız 20 ye eşit değilidir</p>

{% endif %} {% endcomment %}

{% comment %} <ul>
{% for number in numbers  %}
    <li>{{number}}</li> <!-- iki tane süslü paranteze almak değişkenin değerini göstermek içindir-->
{% endfor %}
</ul> {% endcomment %}



{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/bootsrap-min.css" %}" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">    <title>YYBlog</title>
</head>
<body>
 
        {% include "includes/navbar.html" %}
 
        <div style = "margin-top:70px; margin-bottom: 60px;" class= "container">
 
            {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == "info" %}
                        <div class="alert alert-danger">{{ message }}</div>
                        
                        {% else %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                        
                        {% endif %}
 
                        {% endfor %}
                    
                    {% endif %}
            {% block body %}
            
            {% endblock body %}
 
        </div>

        <script src="{% static "js/jquery-3.2.1.js" %}"></script>
        <script src="{% static "js/bootstrap.min.js" %}"></script>
        <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script> <!--Kod Snippet makalelere eklenen kodları renklendirmek için-->
        
       
 
</body>
</html>

templates/layoutArticles.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/bootsrap-min.css" %}" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">    <title>YYBlog</title>
</head>
<body>
 
        {% include "includes/navbarArticles.html" %}
 
        <div style = "margin-top:70px; margin-bottom: 60px;" class= "container">
 
            {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == "info" %}
                        <div class="alert alert-danger">{{ message }}</div>
                        
                        {% else %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                        
                        {% endif %}
 
                        {% endfor %}
                    
                    {% endif %}
            {% block body %}
            
            {% endblock body %}
 
        </div>

        <script src="{% static "js/jquery-3.2.1.js" %}"></script>
        <script src="{% static "js/bootstrap.min.js" %}"></script>
        <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script> <!--Kod Snippet makalelere eklenen kodları renklendirmek için-->
        
       
 
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>

        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }} <!--{{ form.as_p }} şablon etiketi, bir formun alanlarını HTML <p> etiketleri içerisinde göstermek için kullanılır.-->
            <br>
            <button type="submit" class="btn btn-danger">Giriş Yap</button>
        
        </form>

    </div>
  </div>



{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3"> <!--boostrapteki hazır bir responsive tasarım-->
        <h3>Kayıt Ol</h3>
        <hr>
        <form method="post">
            {% csrf_token %} <!--csrf ataklarından kurtulmak için bunu yazmamız lazım-->
            {{form|crispy}} <!--{{form.as_p}}: Bu satır, Django'nun form nesnesini HTML olarak dönüştürür. form.as_p formun tüm alanlarını paragraf etiketleri içinde göstermek için kullanılır. Örneğin, bir form alanı <p> etiketleri arasına alınır. -->
            <br>
            <button type="submit" class="btn btn-danger">Kayıt Ol</button>
        </form>
    </div>
  </div>





{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3>
        <hr>

        <form action="" method="POST" enctype="multipart/form-data"> <!--enctype="multipart/form-data" resim dosyalarınıda eklenmesini sağlıyoruz-->
            {% csrf_token %}
            {{form.media}}
            {{ form|crispy }} <!--{{ form.as_p }} şablon etiketi, bir formun alanlarını HTML <p> etiketleri içerisinde göstermek için kullanılır.-->
            <br>
            <button type="submit" class="btn btn-danger">Güncelle</button>
        
        </form>

    </div>
  </div>



{% endblock body %}